### ISSUE TITLE
Please add --version support

### ISSUE THREAD

**Issue by somaritane** [AbsaOSS/golic#1]
It would be good if golic would be able to return its version if called with `--version` option, in simple format.
This is needed for dependent projects to upgrade to certain golic version only in case of version mismatch.
Example of command output would be:
```
golic --version
v0.4.4
```
or
```
golic --version
Version: v0.4.4
```

**Comment by kuritka** [comment]
Hi, v0.4.5, version support 

![Screenshot 2021-03-18 at 09 34 20](https://user-images.githubusercontent.com/7195836/111596141-20025000-87cd-11eb-8902-47d48f178174.png)
